#!/bin/bash
hex_code=$1
print_color(){
	local color_code=$1
	local text=$2
	echo -e "\e[38;5;${color_code}m${text}\e[0m"
}

hex_code=$1
decimal_code=$((16#${hex_code}))
print_color "${decimal_code}" "${hex_code}"
