#! /bin/sh
sxhkd &
numlockx on &
~/.config/polybar/launch.sh
#polybar top &
#
feh --bg-fill /home/juampa/.config/wallpapers/ae86.jpg &
compton --config /home/juampa/.config/compton/xd.conf &
/usr/bin/lxpolkit &
bspc monitor -d I II III IV V VI
xsetroot -cursor_name left_ptr
bspc config border_width        0.2
#bspc config active_border_color        "#E36B9F"
#bspc config normal_border_color        "#FFFFFF"
bspc config normal_border_color "#ffffff"
bspc config active_border_color "#ffffff"
bspc config focused_border_color  "#92FEC1"
bspc config presel_feedback_color "#6272a4"
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
